version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - checkout
      - run: 
          name: Download up-to-date Docker
          command: curl -fsSL https://get.docker.com/ -o docker-install.sh
      - run: 
          name: Install Docker
          command: sh docker-install.sh
      - run: 
          name: Configure Docker to enable manifest support
          command: |-
            mkdir -p ~/.docker && echo '{"experimental":"enabled"}' > ~/.docker/config.json
      - run:
          name: Enable QEMU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build/push images
          command: export VERSION=$CIRCLE_SHA1; ./scripts/build-containers.sh
      - run:
          name: Push manifest
          command: docker manifest push deviceplane/demo-go:$CIRCLE_SHA1

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
