version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Enable QEMU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - run:
          name: Build image
          command: docker build -t deviceplane/demo-go:$CIRCLE_SHA1 .
      - run:
          name: Docker login
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Deploy image
          command: docker push deviceplane/demo-go:$CIRCLE_SHA1

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
